apiVersion: app/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-backend
  name: deployment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-backend
    spec:
      containers:
      - name: backend
        env:
          - name: REDIS_DNS
            value: db
        image: akirk20/simple-fortune-cookie-backend:latest
        ports:
        - containerPort: 9000
          name: deployment-backend
          protocol: TCP
--- 

apiVersion: v1
kind: Service
metadata:
  name: deployment-backend
  labels:
    app: deployment-backend
spec:
  type: ClusterrIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: deployment-backend
