version: "3.9"
 
services: 

  db: 
    image: redis
    ports: 
      - 6379:6379
    
  backend: 
    build: ../backend/
    ports: 
      - 9000:9000
    depends_on: 
      - "db"
    environment: 
      REDIS_DNS: db

  frontend:
    build: ../frontend/
    ports: 
      - 8080:8080
    depends_on: 
      - "backend" 
    environment: 
      BACKEND_DNS: backend

  

  
  
