version: "3.9"
 
services: 

  db: 
    image: redis
    ports: 
      - 6379:6379
    environment: 
      REDIS_DNS: localhost

  backend: 
    build: ../backend/
    ports: 
      - 9000:9000
    depends_on: 
      - db

  frontend:
    build: ../frontend/
    ports: 
      - 8080:8080
    depends_on: 
      - backend 
    environment: 
      BACKEND_DNS: localhost
      BACKEND_PORT: 9000
  

  
  
