version: "3.9"
 
services: 
  frontend:
    build: ../frontend/
    ports: 
      - 8080:8080
    depends_on: 
      - backend 
    environment: 
      BACKEND_DNS: localhost
      BACKEND_PORT: 9000
  
  backend: 
    build: ../backend/
    ports: 
      - 9000:9000
    depends_on: 
      - db
  
  db: 
    image: Redis
    ports: 
      - 6379:6379
    environment: 
      REDIS_DNS: localhost
