on:
  push:
    branches:
      - "dev/**"

jobs: 
  test:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Testing dev-tests!

